{"name": "test_verify_login_with_valid_credentials", "status": "passed", "start": 1721831430026, "stop": 1721831431855, "uuid": "dff791c7-8821-4258-928b-2f238cd20c67", "historyId": "14f2072526db18090e3cb1e2c1ce29e3", "testCaseId": "14f2072526db18090e3cb1e2c1ce29e3", "fullName": "test.test_Login.TestLogin#test_verify_login_with_valid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Raunak"}, {"name": "thread", "value": "33780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_Login"}]}